# Gambas Action File 3.0

{ Actions
  { Action about
    Text = "About"
    Shortcut = ""
  }
  { Action close
    Text = "Close"
    Shortcut = "Ctrl+W"
  }
  { Action menubar
    Text = "Show Menubar"
    Shortcut = "Ctrl+M"
  }
  { Action open
    Text = "Open"
    Shortcut = "Ctrl+O"
    Picture = "icon:/medium/open"
  }
  { Action quit
    Text = "Quit"
    Shortcut = "Ctrl+Q"
    Picture = "icon:/medium/quit"
  }
  { Action save
    Text = "Save As"
    Shortcut = "Ctrl+S"
    Picture = "icon:/medium/save-as"
  }
  { Action toolbar
    Text = "Show Toolbar"
    Shortcut = ""
  }
}

{ Toolbars
  { Toolbar MainToolbar
    Text = ""
    List = "open,save,quit"
    Default = "open,save,quit,|,-,$lblMode,$optNormal,$optTranslit,$optIgnore,$chkOmit"
  }
}

