# Gambas Action File 3.0

{ Actions
  { Action about
    Text = "About"
    Shortcut = ""
  }
  { Action close
    Text = "Close"
    Shortcut = "Ctrl+W"
  }
  { Action menubar
    Text = "Hide menubar"
    Shortcut = "Ctrl+Alt+M"
  }
  { Action open
    Text = "Open"
    Shortcut = "Ctrl+O"
  }
  { Action quit
    Text = "Quit"
    Shortcut = "Ctrl+Q"
  }
  { Action save
    Text = "Save"
    Shortcut = "Ctrl+S"
  }
}

{ Toolbars
  { Toolbar MainToolbar
    Text = "ToolBar1"
    List = ""
    Default = "$chkOmit,$lblMode,$optNormal,$optTranslit,$optIgnore"
  }
}

